name: Commit And Push

on:
  pull_request:
    types: [opened, reopened]

jobs:
  get_changed_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
      - name: List of files 
        run: |
          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
          FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename' | tr '\n' ' ' | tr '/' '_')
          echo "FILES=${FILES}" >> $GITHUB_ENV
        
      - name: Create files
        run: |
          rm -rf .licenses
          mkdir .licenses
          STRINGS="${{ env.FILES }}"
                                    
          for filename in $STRINGS; do
            echo "$filename"
            touch .licenses/"$filename"
          done
       
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Adding license findings via GitHub Actions"
          echo "Print github ref ${GITHUB_REF}"
          git status
          git branch
          git push
                             
